<?php
# MediaWiki LocalSettings.php Configuration
# This file was automatically generated by the MediaWiki installer.

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "MyCompanyWiki";
$wgMetaNamespace = "MyCompanyWiki";

## The URL base path to the directory containing the wiki;
$wgScriptPath = "/wiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wiki.company.com";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "db.internal.company.com";
$wgDBname = "mediawiki_production";
$wgDBuser = "wiki_user";
$wgDBpassword = "P@ssw0rd123!SecretDB";

# MySQL specific settings
$wgDBprefix = "mw_";
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared memory settings
$wgMainCacheType = CACHE_MEMCACHED;
$wgMemCachedServers = array(
	'10.0.1.15:11211',
	'10.0.1.16:11211',
);

## UPO means: this is also a user preference option
$wgEnableEmail = true;
$wgEnableUserEmail = true;
$wgEmergencyContact = "admin@company.com";
$wgPasswordSender = "wiki@company.com";

$wgEnotifUserTalk = true;
$wgEnotifWatchlist = true;
$wgEmailAuthentication = true;

# SMTP Email settings
$wgSMTP = array(
	'host' => 'smtp.company.com',
	'IDHost' => 'company.com',
	'port' => 587,
	'auth' => true,
	'username' => 'wiki-noreply@company.com',
	'password' => 'SmtpP@ssw0rd456'
);

## Authentication
$wgSecretKey = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef";
$wgAuthenticationTokenVersion = "1";

# LDAP Authentication
$wgAuth = new LdapAuthenticationPlugin();
$wgLDAPDomainNames = array( 'company' );
$wgLDAPServerNames = array( 'company' => 'ldap.company.com' );
$wgLDAPSearchAttributes = array( 'company' => 'sAMAccountName' );
$wgLDAPBaseDNs = array( 'company' => 'dc=company,dc=com' );
$wgLDAPUserBaseDNs = array( 'company' => 'ou=Users,dc=company,dc=com' );
$wgLDAPEncryptionType = array( 'company' => 'ssl' );
$wgLDAPUseLocal = false;
$wgMinimalPasswordLength = 8;

# AWS S3 File Storage
$wgUploadDirectory = "/mnt/wiki/images";
$wgUploadPath = "https://wiki-media.company.com/images";
$wgFileBackends['s3'] = array(
	'name' => 's3',
	'class' => 'AmazonS3FileBackend',
	'lockManager' => 'nullLockManager',
	'awsKey' => 'AKIAIOSFODNN7EXAMPLE',
	'awsSecret' => 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
	'awsRegion' => 'us-west-2',
	'awsBucket' => 'company-wiki-uploads'
);

## Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = "";
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# End of automatically generated settings.
